### ISSUE TITLE
REPORTE: Control diario y acumulado de los indicadores de operaciones por hojas de ruta

### ISSUE THREAD

**Issue by Anabel9112** [amendezm/base-omnibus-app#34]
Fecha:17/11/019 (que se muestre el control diario pero que permita filtrar por día) -  es posible q este reporte coincida con la página de hoja de ruta – verificar y ajustar de ser así
										
Columnas: RUTA, DESTINO, MARCA Ómnibus, CAPACIDAD, INTERCAMBIO DE LA RUTA, No. ÓMNIBUS, Precio. Pasaje, VIAJES, Km GPS, COMBUSTIBLE CONSUMIDO GPS, RECAUDACIÓN

Nota: 
o	Los datos se extraen de las hojas de ruta (HR) analizadas diariamente por la UEB.
o	Debajo, en el mismo reporte, poner tabla igual pero acumulada por meses, pero que se escoja el mes, en un principio que solo se muestre el mes actual y se filtre el mes. Ejemplo:
Mes: (a filtrar)
                                                         Actual: Abril
Columnas: RUTA, DESTINO, MARCA Ómnibus, CAPACIDAD, INTERCAMBIO DE LA RUTA, No. ÓMNIBUS, Precio. Pasaje, VIAJES, Km GPS, COMBUSTIBLE CONSUMIDO GPS, RECAUDACIÓN

Tener en cuenta: 
Rango de intercambiabilidad de pasajeros 
SERVICIOS	                      CAPACIADAD ESTÁTICA (Ce)	      CAPACIADAD DINÁMICA (Cd)
Urbano y Suburbano	                         42	                                 42+(42/2)=63 ó 42*2=84
Interurbano	                                         42	                                 42 ó 42+(42/2)=63
Rural	                                                 42	                                 90% de Ce=38 ó 42
•	El rango de intercambiabilidad de pasajeros puede cambiar dependiendo de la ruta y el servicio que preste la misma.
•	La capacidad estática depende del medio que se emplee para la transportación de pasajero (Diana, Zil, Kamaz, etc.)
•	La capacidad dinámica depende de la capacidad estática.

**Comment by Anabel9112** [comment]
Ale este reporte está fácil es para el control general de las hojas de ruta pero los datos ya están en la bd, si necesitas ayuda para hacerlo con una consulta me avisas

**Comment by Anabel9112** [comment]
Ale de este lo ideal sería hacer el cambio en la bd de la relación gps con HR, si no te da mucho trabajo hazla y así elimina la relación ómnibus con gps

**Comment by Anabel9112** [comment]
Esto te lo pase ayer, pero si cambias la bd varía esto:

SELECT ruta.noruta, ruta.destino, omnibus.noomnibus, tipo_omnibus.tipo, 
tipo_omnibus.capacidad_total, ruta.preciopasaje, hoja_ruta.nohojaruta, hoja_ruta.cantidadviajes, 
g_p_s.kmrecorridos, g_p_s.combustible, recaudacion.recaudacion, hoja_ruta.fecha
FROM public.ruta, public.omnibus, public.tipo_omnibus, public.hoja_ruta, public.g_p_s, public.recaudacion 
WHERE hoja_ruta.id_ruta = ruta.id AND hoja_ruta.id_omnibus = omnibus.id AND 
omnibus.id_tipoomnibus = tipo_omnibus.id AND omnibus.id = g_p_s.id_omnibus AND
hoja_ruta.fecha = g_p_s.fecha AND recaudacion.id_hojaruta = hoja_ruta.id
ORDER BY ruta.noruta DESC;

**Comment by amendezm** [comment]
@Anabel9112 Ok
