### ISSUE TITLE
Cambios en reporte Tarjeta de combustible y GPS

### ISSUE THREAD

**Issue by Anabel9112** [amendezm/base-omnibus-app#39]
Adicionar columna Saldo inicial = saldo antes de asignar nuevo combustible, antes de columna Combustible asignado (usar abreviaturas para las columnas de ser necesario)
Adicionar columna Consumo tarjeta (CHIP) - este dato deben insertarlo
Adicionar columna Saldo final (tarjeta)
Permitir filtrar por día y mes

**Comment by amendezm** [comment]
El filtro de las data tables permite filtrar por cualquier campo. 
Esto significa q todas la tablas tienen filtros para cada una de sus columnas
No creo necesario implementar ese filtro específico

**Comment by amendezm** [comment]
tengo varias dudas aquí

* saldo inicial: este valor debería ser calculado no? (en que momento se asigna el nuevo combustible? creo q ese caso de uso no está implementado)
* consumo tarjeta: dónde se insertaría esto? considero q este valor debería irse incrementando a medida q se habilita combustible. Entonces es necesario asociar las habilitaciones con las tarjetas de combustible (esto nose hace)
* saldo final: esto no lo entiendo

**Qué es lo q debe reflejar este reporte, para ver si se entiende mejor el flujo**
