### ISSUE TITLE
Planificación diaria de combustible

### ISSUE THREAD

**Issue by Anabel9112** [amendezm/base-omnibus-app#40]
Columnas: Ruta (# sin coma), Ómnibus(# sin coma), Cantidad de equipos(#), Km diario(# float o double), Salidas diarias (# sin coma), Consumo diario(# float o double - litros) , Consumo total(# float o double - litros), Gasto total($ float o double)
- Entre parentesis tipo de dato
- Consumo diario = Km diario/Indice de Consumo normado
- Consumo total depende de un valor que deben introducir de la cantidad de días a planificar, ponerlo en la misma interfaz. Entonces CT =Consumo diario x Días a planificar
- Gasto total = CT x precio de combustible (a introducir también)
- Al final de esa tabla debajo una tabla con los acumulados de consumo de combustible del mes solo con las columnas ruta, consumo total y gasto total y al final de esta tabla la sumatorioa para que vean total general

**Comment by amendezm** [comment]
* qué viene siendo la cantidad de equipos?
* los días a planificar no se muestran en la tabla?

**Comment by Anabel9112** [comment]
- cantidad de equipos es el atributo cant de medios en ruta
- los días a planificar es un valor que debe introducir el usuario, pero no lo incluyas en la tabla, solo ponlo encima separado, porque eso es necesario para los cálculos
