### ISSUE TITLE
The general bus report seems to be wrong

### ISSUE THREAD

**Issue by amendezm** [amendezm/base-omnibus-app#46]
![image](https://user-images.githubusercontent.com/26444448/79267713-9e40ce80-7e67-11ea-8aa6-fe1701185077.png)

Review the logic of this report. What is the expected behaviour?
**The are too many repeated fields**

**Comment by Anabel9112** [comment]
Quitar columna fecha de asignación del combustible y envíame foto de la interfaz de ómnibus a ver coherencias.

**Comment by amendezm** [comment]
![image](https://user-images.githubusercontent.com/26444448/79485795-cce3b400-7fe3-11ea-9600-3133f6bda328.png)

**Comment by Anabel9112** [comment]
Recuerda en esa interfaz de ómnibus que tipo es la marca, cambia eso si no lo haz hecho

**Comment by Anabel9112** [comment]
Al primero, reporte general por ómnibus cámbiale el nombre y ponle, reporte de indicadores por ómnibus

**Comment by amendezm** [comment]
Tengo varias dudas, el cambio de tipo por marca no lo había hecho y no me acordaba la razón, me puse a analizar de nuevo...
Existe una relación one to many entre tipo de omnibus y omnibus, ahora la marca dicen q es diana o yutong(q son los tipos actualmente), eso se puede cambiar, es sencillo, solo usar esas dos opciones en el select y decir q es la marca; la duda es en qué se usaría el tipo de omnibus, q por cierto ya ese no sería el nombre, porque los tipos son omnibus, semiomnibus, ferro y lancha. Ya la relacion se pierde entre las 2 entidades porque no hay forma de que un omnibus sea una lancha.
Profe cada cambio de esos hay q analizarlo bien porque implica cambios es el modelo

**Comment by Anabel9112** [comment]
@amendezm Te entiendo, pero ellos explican las cosas primero a una forma y luego se dan cuenta q se equivocaron y uno es el q se jode.
Mira es asi como dices la marca es diana, yutong; pero ten en cuenta q luego pueden añadirse otras marcas. 
Y el tipo es asi como dices y por supuesto q tanto la marca como el tipo en cuanto a la relacion con onmnibus es 1a1
