### ISSUE TITLE
Fuel type is not showing

### ISSUE THREAD

**Issue by amendezm** [amendezm/base-omnibus-app#49]
The controller, routes and components exits, but they are not taked into account

**Comment by amendezm** [comment]
Profe qué hago aquí?

**Comment by amendezm** [comment]
Esa tabla no se estaba mostrando, ya desde la antigua versión. De mostrarse en qué sección iría?

**Comment by Anabel9112** [comment]
Cuál tabla?

**Comment by Anabel9112** [comment]
Necesito ver el software corriendo para entender todo mejor, así me pierdo

**Comment by Anabel9112** [comment]
dime en que interfaz es esto?

**Comment by amendezm** [comment]
@Anabel9112 esto no tiene interfaz
