### ISSUE TITLE
En planes

### ISSUE THREAD

**Issue by Anabel9112** [amendezm/base-omnibus-app#69]
![issue #69](https://user-images.githubusercontent.com/60940900/85956531-54d72a00-b954-11ea-9151-cc2b3fe42d12.jpg)
![issue #69-2](https://user-images.githubusercontent.com/60940900/85956533-59034780-b954-11ea-9064-d300f4df1f99.jpg)
Solo muestra 1 ruta, revisar consulta y cálculos

**Comment by amendezm** [comment]
este esta bien, lo q pasa q hay rutas q no tienen HR asociada, pero esto con datos reales no debe pasar
