### ISSUE TITLE
En pronósticos

### ISSUE THREAD

**Issue by Anabel9112** [amendezm/base-omnibus-app#70]
![issue #70](https://user-images.githubusercontent.com/60940900/85956602-d9c24380-b954-11ea-9227-ff624afc6fcb.jpg)
El toltip de los ptos de la gráfica son de pronóstico y dicen año anterior

**Comment by amendezm** [comment]
profe aqui esta bien, son los dos valores, el anno anterior y el del pronostico, es un tooltip para los 2

**Comment by Anabel9112** [comment]
@amendezm es el mismo? muestra los valores del pronóstico bien pero pone encima año anterior, eso es asi?

**Comment by amendezm** [comment]
@Anabel9112 es como si fuesen 2 tooltips en uno, el color lo diferencia, esta en la leyenda arriba, cual color es cada cual
