### ISSUE TITLE
En reporte horas trabajadas

### ISSUE THREAD

**Issue by Anabel9112** [amendezm/base-omnibus-app#74]
![issue #72](https://user-images.githubusercontent.com/60940900/85956960-3de60700-b957-11ea-8713-c1fd4b50adb1.jpg)
Calcular y pasar para dpto RRHH

**Comment by amendezm** [comment]
a que se refiere con calcular?

**Comment by Anabel9112** [comment]
@amendezm Que se muestren los datos, hacer el reporte
